### ISSUE TITLE
Leverage rtsp-simple-server to reduce load?

### ISSUE THREAD

**Issue by Manouchehri** [seydx/homebridge-camera-ui#505]
There's a very handy application called [rtsp-simple-server](https://github.com/aler9/rtsp-simple-server), which basically allows republishing/proxying RTSP[S]/RTMP streams. 

https://github.com/aler9/rtsp-simple-server

This is extremely useful when dealing with shoddy RTSP and RTMP cameras, as it reduces the load on the camera to just 1 stream, even if multiple clients are connected through rtsp-simple-server. It also significantly reduces initial connection time in my setup, as I have it connected to the rtsp streams even before clients are connected (this can be disabled by using `sourceOnDemand: yes`).

Example `rtsp-simple-server.yml`:
```yml
logLevel: info
logDestinations: [stdout, syslog]
readTimeout: 10s
writeTimeout: 10s
readBufferCount: 512
api: no
metrics: no
pprof: no
runOnConnect:
runOnConnectRestart: no
rtspDisable: no
protocols: [tcp]
encryption: "strict"
# This is Docker's default IP in our setup
rtspsAddress: 172.17.0.1:8555
# openssl genrsa -out server.key 4096
serverKey: server.key
# openssl req -new -x509 -sha256 -key server.key -out server.crt -days 3650
serverCert: server.crt
authMethods: [basic, digest]
readBufferSize: 2048
rtmpDisable: yes
hlsDisable: yes
paths:
  cam1:
    source: rtsp://dave:hunter2@192.168.1.16/live
    sourceProtocol: tcp
    # sourceOnDemand: yes
    readUser: sha256:BdSWkrdV+ZxFBLUQQY7+7uv9RmiSVA8nrPmjGjJtZQQ=
    readPass: sha256:BdSWkrdV+ZxFBLUQQY7+7uv9RmiSVA8nrPmjGjJtZQQ=
  cam2:
    source: rtsp://dave:hunter2@192.168.1.17/live
    sourceProtocol: tcp
    # sourceOnDemand: yes
    readUser: sha256:BdSWkrdV+ZxFBLUQQY7+7uv9RmiSVA8nrPmjGjJtZQQ=
    readPass: sha256:BdSWkrdV+ZxFBLUQQY7+7uv9RmiSVA8nrPmjGjJtZQQ=
```

Then simply use `-rtsp_transport tcp -i rtsps://userpass:userpass@172.17.0.1:8555/cam1` as the source feed.

I'm not entirely sure if it makes sense to add this to [camera.ui](https://github.com/seydx/camera.ui), or as a separate Homebridge plugin. Thoughts?
